modules:
  cloudchest: true
  rolldice: true
  imprint: false
  seal: false
  teleport: false
  showwhotamed: false
  tpsspam: true
  murder: true
  playerTwist: true
  flyTicket: true
players: [ ]
chest: ''