name: MeowUtils
main: fun.miranda.MeowUtils
version: 1.4.3
author: Miranda
description: 猫子组件
softdepend: [ ]
load: POSTWORLD
api-version: 1.20

commands:
  sealscroll:
    description: 给玩家封印卷轴
    usage: /sealscroll <player> <amount>
    permission: meowutils.sealscroll.give
    permission-message: §c你没有权限
  imprint:
    description: 给玩家烙印卷轴
    usage: /imprint <player> <amount>
    permission: meowutils.imprintscroll.give
    permission-message: §c你没有权限
  imprintsign:
    description: 给烙印卷轴签名
    usage: /imprintsign <sign>
  cc:
    description: 打开云箱子
    usage: /cc
  sethome:
    description: 设置家
    usage: /sethome <homeName>
  delhome:
    description: 删除家
    usage: /delhome <homeName>
  defhome:
    description: 设置默认家
    usage: /defhome <homeName>
  home:
    description: 回到指定家
    usage: /home [homeName]
  backcorpse:
    description: 回到上次死亡的地方
    usage: /backcorpse
  rtp:
    description: 随机传送
    usage: /rtp <X> <Y> <Z> <radius> <player>
  tpsspam:
    description: 切换控制台是否持续显示 tps
    usage: /tpsspam
    permission: meowutils.tpsspam
    permission-message: §c你没有权限
  murder:
    description: 清除范围内的指定类型的实体
    usage: /murder <distance> <EntityType...>
    permission: meowutils.murder
    permission-message: §c你没有权限
  ce:
    description: 按照实体类型计数实体数量
    usage: /ce
    permission: meowutils.ce
    permission-message: §c你没有权限
  healthset:
    description: 设置玩家的血量
    usage: /healthset <player> <value>
    permission: meowutils.healthset
    permission-message: §c你没有权限
  tp:
    description: 传送到玩家的位置
    usage: /tp <player>
  tphere:
    description: 将玩家传送到自己的位置
    usage: /tphere <player>
  flyticket:
    description: 给玩家飞行券
    usage: /flyticket <fliTime>
    permission: meowutils.flyticket
    permission-message: §c你没有权限
  openfly:
    description: 切换是否开启飞行
    usage: /openfly